version: "3.9"
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu_container
    ports:
      - "8800:8880"
    volumes:
      - ./app:/var/www/html
    command: ["bash", "-c", "while true; do sleep 30; done"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always

